mods:
    - name: "AutoDeconstruct"
    - name: "Squeak Through"
    - name: "Bottleneck"
    - name: "kry-inserters"
    - name: "Side Inserters" # https://mods.factorio.com/mod/Side%20Inserters
    - name: "YARM" # https://mods.factorio.com/mod/YARM
